### ISSUE TITLE
Cat tags should be individual 'tags'

### ISSUE THREAD

**Issue by Bouncey** [atjonathan/catphotoapp#18]
Not styled like this, but the same idea

![image](https://dab1nmslvvntp.cloudfront.net/wp-content/uploads/2015/01/142261545602.png)

**Comment by atjonathan** [comment]
@Bouncey We can use [Materialize Chips](http://materializecss.com/chips.html) for this.

**Comment by Bouncey** [comment]
I was looking at [materialize tags](http://henrychavez.github.io/materialize-tags/examples/) but couldn't get it working properly, and he's a bit sparse with info. Will take a look at chips

**Comment by Bouncey** [comment]
![tags](https://cloud.githubusercontent.com/assets/18572518/16558695/35d99c28-41df-11e6-816c-19f30aa51fbe.png)

**Comment by atjonathan** [comment]
@Bouncey can we use the same color of blue for the tags and like buttons etc. If you want we can switch the color used in like buttons. Some cool colors: http://materializecss.com/color.html#palette
Other than that, looks awesome :tada:

**Comment by Bouncey** [comment]
That is `blue lighten-4` 

I was only having a play about. Don't want to go too far before the gulp refactor
