### ISSUE TITLE
Cats can be filtered by tag

### ISSUE THREAD

**Issue by Bouncey** [atjonathan/catphotoapp#21]

**Comment by amrsekilly** [comment]
@Bouncey Should the filter be triggered by pressing any of the tags below the image so we need to convert these spans into buttons? Or should there be some specific tags' buttons on top of the page that filter the images?

**Comment by Bouncey** [comment]
I was thinking a click on the tag would filter the images buy that tag. Also a search bar that uses [typeahead](https://twitter.github.io/typeahead.js/). We need to refactor the JS running the app first to eliminate the possibility of spam first.

**Comment by Bouncey** [comment]
No need for `typeahed.js`

Will be implemented with react
