### ISSUE TITLE
tag search disables other images modal

### ISSUE THREAD

**Issue by amrsekilly** [atjonathan/catphotoapp#48]
If you search for a certain tag then you delete that search and go back to the home page you can't expand any image to a modal by clicking on it except for the image that matches the previous tag search.

I'll try to investigate that further.

**Comment by atjonathan** [comment]
This is a known issue thanks!

**Comment by amrsekilly** [comment]
You're welcome! Can I try to fix it?

**Comment by amrsekilly** [comment]
I can't figure it out. I understood every part of the app but I can't understand what's going wrong. The only thing that I noticed happens is the removal of an initialization class from the image's container and the removal of an outer div that holds the class 'material-placeholder' but I don't understand how changing the filter could affect the behavior of material box.

**Comment by amrsekilly** [comment]
I guess it has to do with the initialization of Material Box

**Comment by amrsekilly** [comment]
I fixed it. I'll send a PR now. However, I don't think this is the best solution to the problem, but it fixed the problem.
