### ISSUE TITLE
Can't see my Cat Photo

### ISSUE THREAD

**Issue by Bouncey** [atjonathan/catphotoapp#5]
added this image

![image](https://pbs.twimg.com/profile_images/661188553963995136/0DXhY6Oz.jpg)

Can see the card it is supposed to be on, with title and tags, but no image

**Comment by Bouncey** [comment]
Seems like the issue is https

**Comment by atjonathan** [comment]
@Bouncey, correct. There's nothing can be done with this. It's a mixed content issue.
