### ISSUE TITLE
Like Button Needs Refresh to Update Likes Count

### ISSUE THREAD

**Issue by Bouncey** [atjonathan/catphotoapp#6]
Like Button Needs Refresh to Update Likes Count

**Comment by atjonathan** [comment]
@Bouncey, this was fixed and works fine for me.

**Comment by Bouncey** [comment]
I just tried it today, I cloned the master

**Comment by atjonathan** [comment]
@Bouncey, try both your issues on https://atjonathan.github.io/catphotoapp :+1:

**Comment by Bouncey** [comment]
I did just that.

First click doesn't update button straight after upload.
![anim](https://cloud.githubusercontent.com/assets/18572518/16502915/95f935f2-3f08-11e6-81a2-574bbb5602d1.gif)

**Comment by atjonathan** [comment]
@Bouncey Oh I see what you mean!! Thanks
