### ISSUE TITLE
URL Validation

### ISSUE THREAD

**Issue by atjonathan** [atjonathan/catphotoapp#8]
Users shouldn't be able to add a photo unless the URL ends with `.png`, `.jpg` etc.

**Comment by sanskar-modi** [comment]
will add a regex to check:
+ It is a url
+ ends with valid extension

**Comment by Bouncey** [comment]
@sanskar-modi didn't see your comment here

**Comment by sanskar-modi** [comment]
i am little busy, so thats good that issue got fixed early. :tada:
